#! /usr/bin/env python
"""
standalone code to calculate the dark current for all extensions of the ccds images from imager. the ccd file needs to be the standard DES ccd fits image with the convention of 1 extension corresponding to 2k x 4k with overscans on the sides.
Created by: Jiangang Hao @ Fermilab, 12/6/2010 
"""

import sys
if len(sys.argv) == 1:
    print 'syntax: darkall imageName'
else:
    import numpy as np
    import pylab as pl
    import pyfits as pf
    hdu=pf.open(sys.argv[1])
    nn=len(hdu)
    print '----extension---Position---darkL (ADU)---darkR (ADU)'
    for i in range(1,nn):
        b=pf.getdata(sys.argv[1],i)
        hdr=pf.getheader(sys.argv[1],i)
        darkL=np.median(b[1500:2000,400:440])-np.median(b[1500:2000,10:50])
        darkR=np.median(b[1500:2000,1400:1440])-np.median(b[1500:2000,2110:2150])
        print i,'---',hdr['detpos'],'----',darkL,'----',darkR
