#! /usr/bin/env python                                                                               
import sys
import pyfits as pf
import numpy as np
import pylab as pl

sys.path.append('/home/jghao/research/ggsvn/decam-fermi')
if len(sys.argv) == 1:
    print 'syntax: pixel imagefile extension'
    print '    or: pixel imagefile (for single extension file)'
elif len(sys.argv) == 2:  
    b=pf.getdata(sys.argv[1],1)
    bm=b.mean(axis=0)
    col=np.arange(1,bm.size+1)
    pl.subplot(2,1,1)
    pl.plot(col[0:80],bm[0:80],'bo')
    pl.grid()
    pl.ylabel('pixel value')
    pl.title(sys.argv[1]+'[1]')
    pl.subplot(2,1,2)
    pl.plot(col[-80:],bm[-80:],'ro')
    pl.grid()
    pl.xlabel('column')
    pl.ylabel('pixel value')   
    pl.show()
else:
    b=pf.getdata(sys.argv[1],sys.argv[2])
    bm=b.mean(axis=0)
    col=np.arange(1,bm.size+1)
    pl.subplot(2,1,1)
    pl.plot(col[0:80],bm[0:80],'bo')
    pl.grid()
    pl.ylabel('pixel value')
    pl.title(sys.argv[1]+'['+sys.argv[2]+']')
    pl.subplot(2,1,2)
    pl.plot(col[-80:],bm[-80:],'ro')
    pl.grid()
    pl.xlabel('column')
    pl.ylabel('pixel value')   
    pl.show()

    
