#! /usr/bin/env python 
import sys
sys.path.append('/home/jghao/fmccd')
if len(sys.argv) == 1:
    print 'syntax: sub_img imagefile biasfile targetfile'
else:
    from DECamCCD import *
    from DECamCCD_def import *
    t=Img_sub(imageName=sys.argv[1],biasName=sys.argv[2],subName=sys.argv[3])

